### ISSUE TITLE
Optional types not deserializable?

### ISSUE THREAD

**Issue by vic-cw** [konsoletyper/teavm-flavour#23]
I might be missing something here, but I am under the impression that `RESTClient.factory(SomeResourceWhichReturnsAnOptional)` throws an exception.

> Caused by: java.lang.NullPointerException
>         at org.teavm.flavour.json.emit.JsonDeserializerEmitter.emitIdCheck(JsonDeserializerEmitter.java:222)
>         at org.teavm.flavour.json.emit.JsonDeserializerEmitter.lambda$emitClassDeserializer$20(JsonDeserializerEmitter.java:183)
>         at org.teavm.metaprogramming.impl.MetaprogrammingImpl.proxy(MetaprogrammingImpl.java:300)
>         at org.teavm.metaprogramming.impl.MetaprogrammingImpl.proxy(MetaprogrammingImpl.java:238)
>         at org.teavm.flavour.json.emit.JsonDeserializerEmitter.emitClassDeserializer(JsonDeserializerEmitter.java:172)
>         at org.teavm.flavour.json.emit.JsonDeserializerEmitter.getClassDeserializer(JsonDeserializerEmitter.java:111)
>         at org.teavm.flavour.json.JSON.getClassDeserializer(JSON.java:79)

This might be due to the fact that the object mapper has to be configured with the Jdk8 module.

Is that the case?

**Comment by vic-cw** [comment]
I guess that is the case, since I get the same exception for `LocalDate`

**Comment by ScraM-Team** [comment]
JSON deserialization definitely has some restrictions.  Start with primitives, Strings, and Enums (and contained classes containing those types).  Be sure to return a value for every field -- nulls tend to cause problems.  

The examples are very helpful to see what is possible.

Please post here if you get it working or not.  If you can narrow it to a repeatable example, you can file an issue.

**Comment by ScraM-Team** [comment]
Oh, are you using the latest bintray builds or the older 0.1.0 build from maven central?

**Comment by vic-cw** [comment]
@ScraM-Team thanks for the answer!

Yes I am using 0.1.0 from Maven Central.

I played around, and indeed with different data types things were fine, until I re-introduced either Optional or LocalDate

**Comment by ScraM-Team** [comment]
The 0.1.0 build is over a year old, you should definitely consider trying the bintray release: https://bintray.com/konsoletyper/teavm/teavm-flavour-dev/0.2.0-dev-52

https://bintray.com/konsoletyper/teavm/teavm-flavour-dev/0.2.0-dev-52

**Comment by vic-cw** [comment]
Ok thanks, I'll try.

Do you know if support for these types has been added since?

**Comment by ScraM-Team** [comment]
Sorry, I'm not sure what types were added.

I'm going to start a thread in the forums for Flavour enhancements and feedback on what is trickiest when starting out.

**Comment by konsoletyper** [comment]
Optional types are not supported by Flavour serialization

**Comment by vic-cw** [comment]
@konsoletyper thanks!
