### ISSUE TITLE
Call to Popup.showModal() causing ClassNotFound exception

### ISSUE THREAD

**Issue by mfdewit** [konsoletyper/teavm-flavour#9]
I've got a REST service defined like this:

```
    @POST
    @Path("items")
    void deleteItems(Set<String> keys);
```
This service is called from my view class:
 ```
private Set<String> selectedItems;
 public void deleteSelectedItems() {
        background.run(() -> {
            this.collectionsService.deleteItems(selectedItems);
        }
```
All is well untill I include a call to open a popup in this same view class:
```
public void openPopup() {
        background.run(() -> {
            Popup.showModal(popup);
        });
    }
```
When the showModal method is called, compiling fails with the following stacktrace:

```
Output file built with errors
Error calling proxy method org.teavm.flavour.json.JSON.getClassSerializer(Lorg/teavm/metaprogramming/ReflectClass;)V: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teavm.metaprogramming.impl.UsageGenerator.emitPermutation(UsageGenerator.java:150)
	at org.teavm.metaprogramming.impl.UsageGenerator.lambda$installProxyEmitter$0(UsageGenerator.java:84)
	at org.teavm.dependency.DependencyAnalyzer.schedulePropagation(DependencyAnalyzer.java:267)
	at org.teavm.dependency.DependencyNode.scheduleSingleType(DependencyNode.java:97)
	at org.teavm.dependency.DependencyNode.propagate(DependencyNode.java:68)
	at org.teavm.dependency.DependencyNodeToNodeTransition.propagate(DependencyNodeToNodeTransition.java:53)
	at org.teavm.dependency.DependencyNodeToNodeTransition.consume(DependencyNodeToNodeTransition.java:41)
	at org.teavm.dependency.DependencyAnalyzer.processNodeToNodeTransitionQueue(DependencyAnalyzer.java:634)
	at org.teavm.dependency.DependencyAnalyzer.processQueue(DependencyAnalyzer.java:603)
	at org.teavm.dependency.DependencyAnalyzer.processDependencies(DependencyAnalyzer.java:648)
	at org.teavm.vm.TeaVM.build(TeaVM.java:364)
	at org.teavm.tooling.TeaVMTool.generate(TeaVMTool.java:415)
	at org.teavm.maven.TeaVMCompileMojo.execute(TeaVMCompileMojo.java:98)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:955)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.RuntimeException: Can't find class java.util.function.Supplier$proxy39
	at org.teavm.flavour.json.emit.GenericTypeProvider.lambda$findClass$5(GenericTypeProvider.java:128)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1126)
	at org.teavm.flavour.json.emit.GenericTypeProvider.findClass(GenericTypeProvider.java:124)
	at org.teavm.flavour.json.emit.GenericTypeProvider.lambda$findField$4(GenericTypeProvider.java:82)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1126)
	at org.teavm.flavour.json.emit.GenericTypeProvider.findField(GenericTypeProvider.java:81)
	at org.teavm.flavour.json.emit.JsonSerializerEmitter.emitField(JsonSerializerEmitter.java:304)
	at org.teavm.flavour.json.emit.JsonSerializerEmitter.emitProperties(JsonSerializerEmitter.java:242)
	at org.teavm.flavour.json.emit.JsonSerializerEmitter.lambda$emitClassSerializer$13(JsonSerializerEmitter.java:170)
	at org.teavm.metaprogramming.impl.MetaprogrammingImpl.proxy(MetaprogrammingImpl.java:300)
	at org.teavm.metaprogramming.impl.MetaprogrammingImpl.proxy(MetaprogrammingImpl.java:238)
	at org.teavm.flavour.json.emit.JsonSerializerEmitter.emitClassSerializer(JsonSerializerEmitter.java:165)
	at org.teavm.flavour.json.emit.JsonSerializerEmitter.getClassSerializer(JsonSerializerEmitter.java:107)
	at org.teavm.flavour.json.emit.JsonSerializerEmitter.returnClassSerializer(JsonSerializerEmitter.java:100)
	at org.teavm.flavour.json.JSON.getClassSerializer(JSON.java:63)
	... 39 more
Caused by: java.lang.ClassNotFoundException: java.util.function.Supplier$proxy39
	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.teavm.metaprogramming.impl.MetaprogrammingClassLoader.loadClass(MetaprogrammingClassLoader.java:43)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.teavm.flavour.json.emit.GenericTypeProvider.lambda$findClass$5(GenericTypeProvider.java:126)
	... 53 more

    at org.teavm.flavour.json.JSON.getObjectSerializer(JSON.java:57)
    at org.teavm.flavour.json.JSON.serialize(JSON.java:48)
    at org.teavm.flavour.json.JSON.serialize(JSON.java:41)
    at nl.scuro.fridge.client.collections.CollectionsService$proxy0.deleteItems(FactoryEmitter.java:220)
    at nl.scuro.fridge.client.collections.CollectionsView.lambda$deleteSelectedItems$5(CollectionsView.java:91)
    at nl.scuro.fridge.client.collections.CollectionsView$deleteSelectedItems$lambda$_0.run(CollectionsView.java:90)
    at org.teavm.flavour.widgets.BackgroundWorker.lambda$run$0(BackgroundWorker.java:27)
    at org.teavm.flavour.widgets.BackgroundWorker$run$lambda$_0.run(BackgroundWorker.java:24)
    at java.lang.Thread.run(TThread.java:89)
    at java.lang.Thread.lambda$start$0(TThread.java:63)
    at java.lang.Thread$start$lambda$_0.run(TThread.java:59)
    at org.teavm.platform.Platform.launchThread(Platform.java:182)
```
Replacing the `selectedItems` parameter with a `Collections.EMPTY_SET` will make it compile again. 
How is this possible?

tnx
Mauro

**Comment by konsoletyper** [comment]
This is definitely not a problem with `Popup.showModal`, it's a problem with serialization. Can you provide a self-contained example to reproduce the issue?

**Comment by scxrx-xx** [comment]
Ok, this sucks. I am not able to reproduce this on the self contained example I've made. 
Seems to be a deeper issue then. I will dig deeper and let you know!

**Comment by scxrx-xx** [comment]
I've tracked down the issue to be (probably) related to the use of a Validator.
A self contained example to reproduce can be found here:
https://bitbucket.org/scuro/teavm-error/src/master/

The file src/main/resources/templates/addCollectionPopup.html contains the use of a validator. If I remove the validator code, everything compiles OK. 
Hope you can help me solve this issue.

**Comment by mfdewit** [comment]
Hi, you already find some time to take a look at the example I provided?

**Comment by konsoletyper** [comment]
Sorry, just forgot about it. Looks like there's an issue with REST support. You better avoid declaring REST method with parameters of Set, Map and List. Instead of Set and List you currently can use arrays. Replaceing Set<String> with String[] in CollectionsService helped to solve the problem.

**Comment by mfdewit** [comment]
No problem, sounds like a workable solution. Thanks!
